---
title: "R Notebook"
output: html_notebook
---

Try to scrape FG Injury page using RSelenium because we need to execute javascript.
Reference page:  https://thatdatatho.com/tutorial-web-scraping-rselenium/
https://joshuamccrain.com/tutorials/web_scraping_R_selenium.html

FG page:  https://www.fangraphs.com/roster-resource/injury-report?groupby=all

```{r}

library(RSelenium)
library(netstat)
library(tidyverse)
```
```{r}
rD <- rsDriver(browser="firefox",port=free_port(), 
               chromever=NULL, verbose=F)
remDr <- rD[["client"]]

```

```{r}
#remDr$open()
#remDr$navigate("https://www.fangraphs.com/roster-resource/injury-report?groupby=all")

remDr$navigate("https://www.fangraphs.com/roster-resource/injury-report")




```

```{r}
#navigate to get full table
myelement <- remDr$findElement(using = 'xpath', '//*[@id="root-roster-resource"]/div[2]/div[2]/div/div[2]/div[1]/select')
#'/html/body/div[2]/div[3]/div/div[2]/div[2]/div/div[3]/div[1]/select')
myelement$clickElement()

Sys.sleep(5)

option <- remDr$findElement(using = 'xpath', "//option[contains(., 'Infinity')]")
option$clickElement()
```





```{r}
# Looking for the correct <table> element
#inj <- remDr$findElement(using='class name','table')
html <- remDr$getPageSource()[[1]] %>% read_html() %>% html_nodes("table") %>% html_table()

r15 <- html[c(-1:-14)]
inj <- bind_rows(r15)
inj <- distinct(inj)


inj <- html[[16]]

inj <- rename(inj,Player=Name,MLB=Team)
inj <- addPlayerid(inj)

remDr$close()

```

Kill the Selenium process - how do we kill the window as well?
```{r}
system("taskkill /im java.exe /f")
```

